### ISSUE TITLE
Building on F38

### ISSUE THREAD

**Issue by RedactedSoftware** [20PercentRendered/opensteamclient#12]
Hi, Building on the F38 creates the following output and fails afterwards.

`CMake Error at /usr/share/cmake/Modules/FindProtobuf.cmake:272 (message):
  Error: PROTOBUF_GENERATE_CPP() called without any proto files
Call Stack (most recent call first):
  CMakeLists.txt:134 (protobuf_generate_cpp)
`

**Comment by 20PercentRendered** [comment]
What is F38? Is it a processor or architecture or is it an OS? I haven't heard of it before.

**Comment by RedactedSoftware** [comment]
F38 is fedora 38.

**Comment by 20PercentRendered** [comment]
Ah. Good to hear it got fixed. Bad to hear that it just fixed itself randomly.
