### ISSUE TITLE
How to compile? And what it is?

### ISSUE THREAD

**Issue by ghost** [20PercentRendered/opensteamclient#53]
From README.md I can't clearly understand what exactly it is and why it is important to have Valve's Steam Client to be installed?

I want to achieve this:
I'm fine to download games and updates using Valve's Steam Client or steamcmd.exe utility.
But I did not like keep this junk (steamwebhelper.exe, Friends Chat, Game Overlay, Broadcasting and etc.) running just to play online game.

I see you done a lot of work by reverse engineering Valve's Steam Client. I want ask you:
It is possible to run a minimal steam client (files steamclient.dll, vstdlib_s.dll and tier0_s.dll) without all "junk" mentioned above?
And I see you have some issues with Steam Service? Or not anymore? Because as I understand Steam Service is responsible for VAC working properly.

I'm will be fine with some "dirty" program which call's right functions in right order from dll's mentioned above. Can you point me where in your files I can find this information. And how to compile it on Windows? Using minimal setup (I mean tools for compile).

**Comment by ghost** [comment]
Well, I figured out how to compile using only .NET 8 SDK, but there 2 errors.
![cmd.exe](https://github.com/user-attachments/assets/7401c39b-fdc4-4b01-a344-95ae62bc57fd)

**Comment by Rosentti** [comment]
Ah. You need Git (for Windows) and the C++ compiler tools from VS. Then compile MainExe. Alternatively, just grab the latest release from GH actions.

**Comment by ghost** [comment]
ok, I downloaded release from GH Actions. Why it is so hard to get it working? There are SSL error. Plus why error window is so so big?? It won't fit on 1366x768 screen. Is something else should be installed? Your program are ready to use, or it is draft?
I'm running genuine Windows 8.1. Should I download Windows 10 just to see what OpenSteamClient is?
And why your client try's to download strings_en_all.zip? Valve's Steam Client need to be installed in Program Files (x86)? Because I have it in Steam folder on Desktop.
![SSL-error](https://github.com/user-attachments/assets/0f7bbc47-b3bd-4d4f-9669-829ab038e938)

**Comment by Rosentti** [comment]
I hadn't updated the packages in a while, so it was trying to download old versions. Try now, with a new release from GH actions.

And yes, the readme states Windows 10 or Arch Linux is required. The readme also states this is in heavy development.

**Comment by Rosentti** [comment]
Also, this isn't particularly lightweight at the moment.

**Comment by ghost** [comment]
ok, still same SSL-error. You can delete this issue (not close), since it is not issue. I someday try download Win10 and give it another try.
