### ISSUE TITLE
Stuck at login

### ISSUE THREAD

**Issue by duarm** [20PercentRendered/opensteamclient#6]
After trying to login, I'm stuck at this screen
![qwdqwdq](https://github.com/20PercentRendered/opensteamclient/assets/26150581/3236fa6d-3b43-4cb9-9c7f-ac267436c674)

**Comment by 20PercentRendered** [comment]
Could you upload the content of `.steam/steam/logs/connection_log.txt`, censoring your accountid (in a format of [U:?:?????????] and/or a long number)?

**Comment by duarm** [comment]
here, I think it logged my multiple tries
[connection_log.txt](https://github.com/20PercentRendered/opensteamclient/files/11593648/connection_log.txt)

**Comment by 20PercentRendered** [comment]
Please retest? This may have been fixed.

**Comment by SFort** [comment]
@duarm pretty please share the skin/style you use to make the login window orange (looks very neat)

**Comment by duarm** [comment]
> Please retest? This may have been fixed.

Sorry for the delay, github did not notify me of the fix, despite being subscribed

It worked!

> pretty please share the skin/style you use to make the login window orange (looks very neat)

it's my own qt6 theme, here are the colors I use with qt6ct
[sakura.conf.txt](https://github.com/20PercentRendered/opensteamclient/files/11854391/sakura.conf.txt)

**Comment by 20PercentRendered** [comment]
Ok in that case looks like this is an intermittent issue. How the hell it's bugged I don't know. Maybe some sort of concurrency issue?

**Comment by SFort** [comment]
i got the same thing when i used a missmatched steamclient.so, guessing it's that

**Comment by 20PercentRendered** [comment]
Could be.
