### ISSUE TITLE
Compile error with -DNOWEBVIEW=ON 

### ISSUE THREAD

**Issue by hurricane-dorian** [20PercentRendered/opensteamclient#7]
Setting it skips checking for QTwebengine however during build it still tries to compile with it 

[ 45%] Building CXX object CMakeFiles/opensteam.dir/src/client/gui/dynamicwebviewlibrarymanager.cpp.o
In file included from /Games/AUR/opensteam-git/src/opensteamclient/src/client/gui/dynamicwebviewlibrarymanager.cpp:3:
/Games/AUR/opensteam-git/src/opensteamclient/src/client/gui/../../dynamicwebview/dynamicwebviewinterface.h:4:10: fatal error: QWebEngineView: No such file or directory
    4 | #include <QWebEngineView>

**Comment by 20PercentRendered** [comment]
Fixed in new commit. Please retry.

**Comment by SFort** [comment]
i also had this issue and can confirm it's fixed my side.
when trying to launch opensteam i get `Failed to load steamclient.so` should i open a issue on it or are you supposed to copy it over manually in the alpha?

**Comment by 20PercentRendered** [comment]
It should be downloaded automatically, but it is kind of buggy and sometimes requires a couple starts to get it going.

**Comment by SFort** [comment]
i deleted the comment because i wasn't certain if it was fixed
compiled it a few more times and seames to be pretty reliable now 

it also doesn't seam to need qt6-webengine as a dep anymore.

>couple starts to get it going

cool i'm gonna take that as open a seperate issue to not clog this one

**Comment by 20PercentRendered** [comment]
Yep. Closing this one.
